### ISSUE TITLE
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

### ISSUE THREAD

**Issue by Gonzih** [slagyr/mmemail#4]
Hi, nice library, but I'm stuck with issue while trying to send email via gmail.

``` clojure

(def mailer (create-mailer {:host "smtp.gmail.com"
                            :port 465
                            :ssl true
                            :user (get (System/getenv) "GMAIL_USER")
                            :password (get (System/getenv) "GMAIL_PASS")
                            :to "some@email.com"
                            :subject "Notice"}))

(mailer {:body "Hello"})
```

```
Exception in thread "main" javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 25;
  nested exception is:
        javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1706)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:525)
        at javax.mail.Service.connect(Service.java:313)
        at javax.mail.Service.connect(Service.java:172)
        at javax.mail.Service.connect(Service.java:121)
        at javax.mail.Transport.send0(Transport.java:190)
        at javax.mail.Transport.send(Transport.java:120)
        at mmemail.helper$deliver_message.invoke(helper.clj:57)
        at mmemail.core$create_mailer$fn__720.invoke(core.clj:12)
        at irr_by_notify.notify$item.invoke(notify.clj:29)
        at irr_by_notify.memoization$check_for_new.invoke(memoization.clj:24)
        at irr_by_notify.core$_main.doInvoke(core.clj:5)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:411)
        at user$eval16.invoke(NO_SOURCE_FILE:1)
        at clojure.lang.Compiler.eval(Compiler.java:6511)
        at clojure.lang.Compiler.eval(Compiler.java:6501)
        at clojure.lang.Compiler.eval(Compiler.java:6477)
        at clojure.core$eval.invoke(core.clj:2797)
        at clojure.main$eval_opt.invoke(main.clj:297)
        at clojure.main$initialize.invoke(main.clj:316)
        at clojure.main$null_opt.invoke(main.clj:349)
        at clojure.main$main.doInvoke(main.clj:427)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:419)
        at clojure.lang.AFn.applyToHelper(AFn.java:163)
        at clojure.lang.Var.applyTo(Var.java:532)
        at clojure.main.main(main.java:37)
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:542)
        at sun.security.ssl.InputRecord.read(InputRecord.java:374)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:850)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1190)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1217)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1201)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:503)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:234)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1672)
        ... 27 more

```

Mb I'm doing something wrong?

Thanks!

**Comment by zarkone** [comment]
had the same issue in `postal`, try to remove `:port` -- worked in my case

**Comment by cmal** [comment]
Same problem:
```
mail> config
{:host "smtp.163.com", :port 465, :ssl true, :user "xxx", :password "xxx", :to "xxx", :subject "xxx", :body nil}
mail> (def mailer (create-mailer config))
#'mail/mailer
mail> (mailer {:body "xxxxx"})
SSLException Unrecognized SSL message, plaintext connection?  sun.security.ssl.InputRecord.handleUnknownRecord (InputRecord.java:710)
Exception in thread "main" javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 25;
```

@Gonzih Hi, how did you solve this problem?

**Comment by cmal** [comment]
> had the same issue in `postal`, try to remove `:port` -- worked in my case

`:port` is required in params.

![image](https://user-images.githubusercontent.com/1773318/79940604-cdbd8f80-8494-11ea-92cf-3cd1fbcb16ff.png)

**Comment by inquisitor-svg** [comment]
turn off ssl

**Comment by inquisitor-svg** [comment]
That's is really weird... But work for me
